---
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This is makes the container able to access the docker daemon itself and run docker commands. IE: You can execute docker command son the host machine.
      - tsdproxydata:/data
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=${TS_AUTH_KEY}
      # Address of docker server (access to example.com ports)
      #- TSDPROXY_HOSTNAME=10.42.37.238           # TODO: I Don't think this is needed or maybe even used.....
      - DOCKER_HOST=unix:///var/run/docker.sock  # Unix is a form of inter-processor communication. This is the path to the docker unix socket file, which allows the container execute docker commands on the host. This is also possibly not required.....
    restart: unless-stopped

  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-rocm}
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ollama"
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=10.3.0'
    pull_policy: always
    tty: true
    restart: unless-stopped

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=' # TODO: Must get this
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "bleardai"
    depends_on:
      - ollama
    restart: unless-stopped

  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"

volumes:
  ollama: {}
  open-webui: {}
  tsdproxydata: {}