{
 "title": "AMD GPU Nodes",
 "description": "Dashboard to visualize AMD GPU metrics using Prometheus Data Source via amd_smi_exporter job",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance:", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "amd_gpu_use_percent{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amd_gpu_use_percent{gpu_use_percent=~\"0|1|2|3|4|5|6|7\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "amd_gpu_memory_busy_percent{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Mem Total Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amd_gpu_memory_busy_percent{gpu_memory_busy_percent=~\"0|1|2|3|4|5|6|7\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "amd_gpu_power_avg_Watts{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(amd_gpu_power_avg_Watts{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "amd_gpu_current_temperature_Celcius{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(amd_gpu_current_temperature_Celcius{gpu_current_temperature=~\"0|1|2|3|4|5|6|7\",instance=\"$instance\"})"
    }
   ]
  }
 ]
}